### ISSUE TITLE
Unable to login after initial boot

### ISSUE THREAD

**Issue by nhippenmeyer** [PiOven/builder#8]
When booting up a pi with Raspian Jessie/Stretch for the first time the login prompt disappears for a second after logging in with the correct credentials and then reappears.   This happens continuously preventing successful authentication.

Also seeing `[FAILED] Failed to start /etc/rc.local Compatibility.` on boot. Unsure if this is related or not.

**Comment by riggerthegeek** [comment]
That `/etc/rc.local` error does sound related to me.

Can you do the following please:
1. Run `git rev-parse HEAD` and tell me the commit ID you're using to generate it
2. Send me all the files you generated so I can run it too (can stick them on a server, Dropbox, Google Drive and email link to simon@simonemms.com)
3. Are you trying to connect using the password or the SSH key?

**Comment by nhippenmeyer** [comment]
I just uploaded the whole repository with the generated `dist` directory to Google Drive and shared it with you.  The output of `git rev-parse HEAD` is `920cead3acf742870e23f54d7594311f97aa0818`.

Below is the output of the `make build` command:

```bash
make docker-run CMD="sh ./scripts/pibuilder.sh"
mkdir -p ./dist/cache
mkdir -p ./dist/ssh-keys
touch ./dist/settings.sh
docker run \
		-it \
		--privileged \
		--rm \
		-v "/Users/nhippenmeyer/src/pibuilder/dist/settings.sh:/opt/pibuilder/settings.sh" \
		-v "/Users/nhippenmeyer/src/pibuilder/dist/cache:/opt/pibuilder/cache" \
		-v "/Users/nhippenmeyer/src/pibuilder/dist/ssh-keys:/ssh-keys" \
		-v "/Users/nhippenmeyer/src/pibuilder/scripts:/opt/pibuilder/scripts" \
		-u 0 \
		riggerthegeek/pibuilder \
		sh ./scripts/pibuilder.sh
Archive:  ./cache/os.e84e7d54f131900610ffeb294f4e2b55.zip
  inflating: ./cache/unzip/2018-03-13-raspbian-stretch.img
umount: /media/rpi_boot: not mounted.
umount: /media/rpi_root: not mounted.
--- Finished successfully ---
username: fc
password: sdnM32b1ZXv8X14NEYmr1INBI1IHdI0N
-----------------------------
Now write ./dist/cache/os.img to an SD card and put into a Pi. This will take up to 5 minutes to configure
```

I'm trying to access the pi via the password prompt when booting it up directly.  I've also confirmed that it hasn't been able to connect to the network so I haven't been able to verify that SSH access works correctly.

**Comment by riggerthegeek** [comment]
Thanks @nhippenmeyer. Got your files too. Probably won't be able to investigate much until tomorrow at the earliest, but I'll definitely investigate this

**Comment by nhippenmeyer** [comment]
@riggerthegeek have you had a chance to look into why the startup script is failing? If you point me in the right direction I could also take a look.

**Comment by riggerthegeek** [comment]
Hey @nhippenmeyer, I'm planning on looking at it tomorrow morning. My in-laws are over at the moment, but they're leaving me home alone tomorrow :fireworks: :fireworks: :fireworks: :fireworks:

**Comment by nhippenmeyer** [comment]
Awesome thanks so much!!

**Comment by riggerthegeek** [comment]
It looks like the issue is related to the base image we're using. I tend to use `https://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2017-07-05/2017-07-05-raspbian-jessie-lite.zip` and you've got `https://downloads.raspberrypi.org/raspbian/images/raspbian-2018-03-14/2018-03-13-raspbian-stretch.zip`. It's both a different build (14th March 2018 vs 5th July 2017) and I use the Lite version (I don't imagine that's the problem though).

I think we may need to do more extensive testing on different base images and then amend the scripts accordingly.

**Comment by riggerthegeek** [comment]
Looks like there are a couple of changes with Jessie and Stretch versions of Raspbian. It seems the Stretch corrected a couple of things and my `/first_run.sh` script was doing it wrong. Pleasingly, the answers were in the logs (always worth checking out `/var/log/rc.local.log` with errors on the Pi)

List of things in order as I found them:

1. The change hostname script was set as `/etc/init.d/hostname.sh`. This doesn't exist in Stretch. Now using `hostnamectl set-hostname <NAME>` which works for both
2. The Docker setup was previously using the https://get.docker.com script. Have changed to using the instructions on https://docs.docker.com/install/linux/docker-ce/debian/#upgrade-docker-after-using-the-convenience-script
3. The `usermod` in the `/first_run.sh` script doesn't set the default shell. Added a `--shell /bin/bash` to the command

**Comment by riggerthegeek** [comment]
Hey @nhippenmeyer, I've created a branch called `feature/cross-raspbian` with some fixes in. Can you try it out please?

One caveat - the Docker installer isn't working so make sure the `PI_INSTALL_DOCKER` variable in `settings.sh` is set to `false`. I need to understand why this isn't working, but this should enable you to do everything else you need to do in various different versions of Raspbian

**Comment by riggerthegeek** [comment]
@nhippenmeyer Nope, no ethernet connection required. Mine works fine just connected via my 2G hotspot.

You need to restart the Pi for the static IP address to be registered after the initial boot though. See the comment in https://github.com/PiOven/builder/blob/master/README.md#run for reasons why

**Comment by nhippenmeyer** [comment]
Got it.  My `/etc/rc.local` configuration is still failing, on both master and the `feature/cross-raspbian` branches and with all the default options (including the `2017-07-05-raspbian-jessie-lite` OS).  I'm attaching the logs from `/var/log/rc.local.log` below:

```bash
+ set -e
+ DATA_DIR=/opt/data
+ useradd -m fc -G sudo
+ echo fc:bm3liX9O
+ chpasswd
+ install -d -m 700 /home/fc/.ssh
+ mv /id_rsa.pub /home/fc/.ssh/authorized_keys
+ chown fc:fc -Rf /home/fc/.ssh/
+ echo fc ALL=(ALL) NOPASSWD: ALL
+ rm /etc/sudoers.d/010_pi-nopasswd
+ deluser -remove-home pi
Looking for files to backup/remove ...
Removing files ...
Removing user `pi' ...
Warning: group `pi' has no more members.
Done.
+ usermod -u 1000 fc
+ groupmod -g 1000 fc
+ shuf /opt/data/words.txt -n 1
+ sed -e s/\s/-/g
+ randomWord1=ingrid
+ shuf /opt/data/words.txt -n 1
+ sed -e s/\s/-/g
+ randomWord2=thomas
+ PI_CONFIG_HOSTNAME=fc-ingrid-thomas
+ echo fc-ingrid-thomas
+ OLD_HOST=raspberrypi
+ sed -i s/raspberrypi/fc-ingrid-thomas/g /etc/hosts
+ /etc/init.d/hostname.sh
+ test  = 16
+ test  = 32
+ test  = 64
+ test  = 128
+ test  = 256
+ apt-get -qq update
W: Failed to fetch http://mirrordirector.raspbian.org/raspbian/dists/jessie/InRelease  

W: Failed to fetch http://archive.raspberrypi.org/debian/dists/jessie/InRelease  

W: Failed to fetch http://archive.raspberrypi.org/debian/dists/jessie/Release.gpg  Temporary failure resolving 'archive.raspberrypi.org'

W: Failed to fetch http://mirrordirector.raspbian.org/raspbian/dists/jessie/Release.gpg  Temporary failure resolving 'mirrordirector.raspbian.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.
+ apt-get install -y python-dev python-pip
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  libexpat1-dev libpython-dev libpython2.7-dev python-chardet python-colorama
  python-distlib python-html5lib python-ndg-httpsclient python-openssl
  python-pkg-resources python-pyasn1 python-requests python-setuptools
  python-six python-urllib3 python-wheel python2.7-dev
Suggested packages:
  python-genshi python-lxml python-openssl-doc python-openssl-dbg
  python-distribute python-distribute-doc doc-base
Recommended packages:
  python-dev-all
The following NEW packages will be installed:
  libexpat1-dev libpython-dev libpython2.7-dev python-chardet python-colorama
  python-dev python-distlib python-html5lib python-ndg-httpsclient
  python-openssl python-pip python-pkg-resources python-pyasn1 python-requests
  python-setuptools python-six python-urllib3 python-wheel python2.7-dev
0 upgraded, 19 newly installed, 0 to remove and 0 not upgraded.
Need to get 19.6 MB of archives.
After this operation, 31.4 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  libexpat1-dev libpython2.7-dev libpython-dev python-pkg-resources
  python-chardet python-colorama python2.7-dev python-dev python-distlib
  python-six python-html5lib python-openssl python-ndg-httpsclient
  python-urllib3 python-requests python-setuptools python-pip python-pyasn1
  python-wheel
E: There are problems and -y was used without --force-yes
```

**Comment by riggerthegeek** [comment]
@nhippenmeyer Looks like the `apt-get` stuff is failing on the `python-dev` package. That started happening randomly for me the other day.

Leave it with me

**Comment by riggerthegeek** [comment]
Hey @nhippenmeyer, I've had a bit of a think about this issue. One thing it's done is highlight a lot of shortcomings in my original approach - it's mildly irritating I didn't get it right first time, but I'm mostly pleased because I think I know how to fix it and it'll be a much better final product. I'm going to effectively can everything I've done so far and start this from the ground up.

One thing I've just fixed though is the static IP issue mentioned a couple of days ago and is now in `master` branch. Again, I only found this because of investigations in this issue so thanks. One thing this project definitely works on today is in [Raspbian Jessie](https://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2017-07-05/2017-07-05-raspbian-jessie-lite.zip) if that's of any use to you

**Comment by nhippenmeyer** [comment]
@riggerthegeek the tool still doesn't work for me on master, using all the default options. With wifi enabled the startup script fails with the error posted above, and with wifi disabled using ethernet the startup script succeeds however still fails to assign a static IP address (see the output of `ifconfig` below):

```bash
lo	Link encap:Local Loopback
	inet addr:127.0.0.1  Mask:255.0.0.0
	inet6 addr: ::1/128 Scope:Host
	UP LOOPBACK RUNNING  MTU:65536 Metric:1
	RX packets:0 errors:0 dropped:0 overruns:0 frame:0
	TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
	collisions:0 txqueuelen:1
	RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

I look forward to trying out your rewrite and let me know if there's anything I can do to assist!

**Comment by nhippenmeyer** [comment]
Hey @riggerthegeek, any updates on the rewrite? I'm eager to try it out when you have something working 😃

**Comment by riggerthegeek** [comment]
Yes, I am working on this as time permits. Currently moving house, but work in progress is in `develop` branch

**Comment by nhippenmeyer** [comment]
👍good luck with the move!

**Comment by riggerthegeek** [comment]
I've made a new version of this application which addresses most of the issues. This can be found on [GitLab](https://gitlab.com/pi-oven/builder)
